### ISSUE TITLE
StreamChat.getInstance is timing out lambda

### ISSUE THREAD

**Issue by FeTree** [GetStream/stream-chat-js#1102]
Hello, we recently upgraded from version 7.1.0 to 8.2.1 and our lambas started timing out. 

Sometimes the lambda throws this: `Task timed out after 6.07 second`

Other times the lambda throws this: 
```
{
    "errorType": "TypeError",
    "errorMessage": "(0 , node_1.getStreamChatClient) is not a function",
    "stack": [
        "TypeError: (0 , node_1.getStreamChatClient) is not a function",
        "    at Object.92030 (/var/task/src/streamWebhookEventProcessor.js:73559:47)",
        "    at __webpack_require__ (/var/task/src/streamWebhookEventProcessor.js:92294:42)",
        "    at Object.71312 (/var/task/src/streamWebhookEventProcessor.js:73383:22)",
        "    at __webpack_require__ (/var/task/src/streamWebhookEventProcessor.js:92294:42)",
        "    at Object.64543 (/var/task/src/streamWebhookEventProcessor.js:75931:16)",
        "    at __webpack_require__ (/var/task/src/streamWebhookEventProcessor.js:92294:42)",
        "    at Object.48414 (/var/task/src/streamWebhookEventProcessor.js:75885:22)",
        "    at __webpack_require__ (/var/task/src/streamWebhookEventProcessor.js:92294:42)",
        "    at Object.41261 (/var/task/src/streamWebhookEventProcessor.js:80157:16)",
        "    at __webpack_require__ (/var/task/src/streamWebhookEventProcessor.js:92294:42)"
    ]
}
```
Our getStreamChatClient function: 
```
export const getStreamChatClient = (
  apiKey: string,
  apiSecret: string
): StreamChat => {
  return StreamChat.getInstance(apiKey, apiSecret, {
    allowServerSideConnect: true,
  });
};
```

Any help would be appreciated, thanks!

**Comment by FeTree** [comment]
We had a circular dependency issue across our services so exports were not getting translated properly. Don't ignore warnings! :p
