### ISSUE TITLE
secretOrPrivateKey is not valid key material

### ISSUE THREAD

**Issue by tayormi** [GetStream/stream-chat-js#1157]
I am using a Supabase edge function to create tokens. 
When I call
```
const client = StreamChat.getInstance<StreamType>(
    Deno.env.get("GETSTREAM_API_KEY") as string,
    Deno.env.get("GETSTREAM_API_KEY_SECRET") as string,
);
```
I get the error below.

```
Error: secretOrPrivateKey is not valid key material
    at Object.de.exports [as sign] (https://esm.sh/v131/jsonwebtoken@9.0.1/deno/jsonwebtoken.mjs:10:10146)
    at Re (https://esm.sh/v131/stream-chat@8.10.1/deno/stream-chat.mjs:7:17877)
    at new o (https://esm.sh/v131/stream-chat@8.10.1/deno/stream-chat.mjs:7:20595)
    at new o (https://esm.sh/v131/stream-chat@8.10.1/deno/stream-chat.mjs:8:13970)
    at Function.value (https://esm.sh/v131/stream-chat@8.10.1/deno/stream-chat.mjs:8:59543)
    at 
```

I have battled this for days and I am on the verge of giving up.

**Comment by rlee1990** [comment]
I got the same error not sure if its because of Deno or the package.

**Comment by tkorsback** [comment]
I have the exakt same error when using supabase edge functions.

Did you have any progress with this?

**Comment by rahuldubey093** [comment]
Anyone found the solution yet?

**Comment by MartinCupela** [comment]
Hello, this issue appears when the secret value is not string. Are you sure you have the secret string available in the runtime and is it a string?
