### ISSUE TITLE
I tried using this with heroku and one way or the other `ws` module is not found

### ISSUE THREAD

**Issue by theo4u** [GetStream/stream-chat-js#58]
I checked your pkg.json and `ws` was in there as a dependency, I don't know why it can't resolve itself when hosted with Heroku. But doing `npm i ws` fixed it. 

FYI: this worked locally without having to install `npm i ws`.

### log

```sh
Error: Cannot find module 'ws'
2019-06-20T07:45:36.010066+00:00 app[web.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2019-06-20T07:45:36.010068+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2019-06-20T07:45:36.010074+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:690:17)
2019-06-20T07:45:36.010076+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:25:18)
2019-06-20T07:45:36.010078+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/isomorphic-ws/node.js:3:18)
2019-06-20T07:45:36.010080+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:776:30)
2019-06-20T07:45:36.010082+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
2019-06-20T07:45:36.010084+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:653:32)
2019-06-20T07:45:36.010086+00:00 app[web.1]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2019-06-20T07:45:36.010087+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

I checked the log, it's pointing to `isomorphic` which requires `Node` and `ws` installed https://github.com/heineiuo/isomorphic-ws#readme

Maybe update your readme to show we need `ws` to make this sdk work

**Comment by tschellenbach** [comment]
so yeah looks like we need to list `ws` as a dep. @jaapbakker88 what do you think?

**Comment by ferhatelmas** [comment]
`ws` is deps, closing. @theo4u if this is still an issue, let us know.

**Comment by ObserverMoment** [comment]
Hi, I have just experienced this issue when pushing my API to Heroku production app.

```
2021-12-31T15:11:00.418580+00:00 app[web.1]: internal/modules/cjs/loader.js:905
2021-12-31T15:11:00.418592+00:00 app[web.1]:   throw err;
2021-12-31T15:11:00.418592+00:00 app[web.1]:   ^
2021-12-31T15:11:00.418592+00:00 app[web.1]: 
2021-12-31T15:11:00.418593+00:00 app[web.1]: Error: Cannot find module 'ws'
2021-12-31T15:11:00.418593+00:00 app[web.1]: Require stack:
2021-12-31T15:11:00.418594+00:00 app[web.1]: - /app/node_modules/isomorphic-ws/node.js
2021-12-31T15:11:00.418594+00:00 app[web.1]: - /app/node_modules/stream-chat/dist/index.js
2021-12-31T15:11:00.418594+00:00 app[web.1]: - /app/dist/lib/getStream.js
2021-12-31T15:11:00.418595+00:00 app[web.1]: - /app/dist/graphql/resolvers/club/club.js
2021-12-31T15:11:00.418595+00:00 app[web.1]: - /app/dist/graphql/resolvers/resolvers.js
2021-12-31T15:11:00.418595+00:00 app[web.1]: - /app/dist/index.js
2021-12-31T15:11:00.418603+00:00 app[web.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
2021-12-31T15:11:00.418603+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
2021-12-31T15:11:00.418604+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:974:19)
2021-12-31T15:11:00.418604+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:93:18)
2021-12-31T15:11:00.418604+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/isomorphic-ws/node.js:3:18)
2021-12-31T15:11:00.418605+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2021-12-31T15:11:00.418605+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2021-12-31T15:11:00.418605+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:950:32)
2021-12-31T15:11:00.418606+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2021-12-31T15:11:00.418606+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:974:19) {
2021-12-31T15:11:00.418606+00:00 app[web.1]:   code: 'MODULE_NOT_FOUND',
2021-12-31T15:11:00.418607+00:00 app[web.1]:   requireStack: [
2021-12-31T15:11:00.418607+00:00 app[web.1]:     '/app/node_modules/isomorphic-ws/node.js',
2021-12-31T15:11:00.418607+00:00 app[web.1]:     '/app/node_modules/stream-chat/dist/index.js',
2021-12-31T15:11:00.418608+00:00 app[web.1]:     '/app/dist/lib/getStream.js',
2021-12-31T15:11:00.418608+00:00 app[web.1]:     '/app/dist/graphql/resolvers/club/club.js',
2021-12-31T15:11:00.418608+00:00 app[web.1]:     '/app/dist/graphql/resolvers/resolvers.js',
2021-12-31T15:11:00.418608+00:00 app[web.1]:     '/app/dist/index.js'
2021-12-31T15:11:00.418609+00:00 app[web.1]:   ]
2021-12-31T15:11:00.418609+00:00 app[web.1]: }
2021-12-31T15:11:00.429587+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-12-31T15:11:00.429770+00:00 app[web.1]: npm ERR! errno 1
```

My local, dev and staging apps in the same pipeline all work fine. 

Any ideas?

Using latest version `5.1.0`

Thanks,

Richard
